name: Node.js Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::459964240689:role/ec2-test-s3-full-access
          aws-region: "ap-northeast-2"
      - run: npm install aws-sdk
      - run: node index.js
